name: Rust

on:
  push:
    paths:
      - "**.rs"
      - "**.yml"
      - "**.toml"
      - "**.wit"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.rs"
      - "**.yml"
      - "**.toml"
      - "**.wit"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        default: true
        toolchain: nightly
        target: wasm32-wasi
    - name: Install WasmEdge
      run: |
        curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.13.3
    - name: Build
      run: cargo build --target wasm32-wasi --verbose
